# Generated by Django 4.1.7 on 2023-02-15 15:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("surname", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                ("datetime", models.DateField(verbose_name="Дата рождения")),
                ("experience", models.IntegerField(verbose_name="Стаж работы")),
            ],
            options={
                "verbose_name": "Информация о докторе",
                "verbose_name_plural": "Добавить доктора",
            },
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("surname", models.CharField(max_length=255, verbose_name="Фамилия")),
                (
                    "patronymic",
                    models.CharField(max_length=255, verbose_name="Отчество"),
                ),
                (
                    "phone_number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(100000000000),
                            django.core.validators.MaxValueValidator(9999999999999),
                        ],
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(verbose_name="Назначить Дату и Время Приема"),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="doctor.doctor",
                        verbose_name="Выбрать Врача",
                    ),
                ),
            ],
            options={
                "verbose_name": "Запись на Прием",
                "verbose_name_plural": "Запись на прием",
            },
        ),
    ]
