# Generated by Django 4.1.7 on 2023-02-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0006_alter_review_author_alter_review_doctor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateTimeField(verbose_name='Назначить Дату и Время Приема'),
        ),
    ]
