# Generated by Django 4.1.7 on 2023-03-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0013_remove_doctor_surname_doctor_education_doctor_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="doctor",
            name="education",
            field=models.TextField(null=True, verbose_name="Образование"),
        ),
        migrations.AlterField(
            model_name="doctor",
            name="post",
            field=models.CharField(max_length=50, null=True, verbose_name="Должность"),
        ),
    ]
