# Generated by Django 4.1.7 on 2023-03-17 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0015_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "verbose_name": "услугу",
                "verbose_name_plural": "Информация об услугах",
            },
        ),
        migrations.RemoveField(
            model_name="record",
            name="name",
        ),
        migrations.RemoveField(
            model_name="record",
            name="patronymic",
        ),
        migrations.RemoveField(
            model_name="record",
            name="surname",
        ),
        migrations.AddField(
            model_name="record",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.service",
                verbose_name="Выбрать Услугу",
            ),
        ),
    ]
