# Generated by Django 4.1.7 on 2023-03-17 15:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0016_alter_service_options_remove_record_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={
                "verbose_name": "услуга",
                "verbose_name_plural": "Информация об услугах",
            },
        ),
    ]
