# Generated by Django 4.1.7 on 2023-03-18 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("doctor", "0021_alter_review_doctor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="doctor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="doctor.doctor",
                verbose_name="Выберите доктора",
            ),
        ),
    ]
